import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import { useLang } from "@/lib/i18n";

const Section = ({ title, children }) => (
  <div style={{ marginBottom: "2rem" }}>
    <h2 style={{ fontSize: "1.1rem", fontWeight: 600, color: "#3a2e24", marginBottom: "0.75rem", fontFamily: "'Inter', sans-serif" }}>{title}</h2>
    {children}
  </div>
);

const P = ({ children }) => (
  <p style={{ fontSize: "0.9rem", color: "#555", lineHeight: 1.8, marginBottom: "0.75rem", fontFamily: "'Inter', sans-serif" }}>{children}</p>
);

const Li = ({ children }) => (
  <li style={{ fontSize: "0.9rem", color: "#555", lineHeight: 1.8, marginBottom: "0.4rem", fontFamily: "'Inter', sans-serif" }}>{children}</li>
);

export default function TermsOfService() {
  const { lang } = useLang();
  const isPl = lang === "pl";

  return (
    <div style={{ background: "#FAFAF8", minHeight: "100vh" }}>
      <Navbar />
      <div style={{ maxWidth: 860, margin: "0 auto", padding: "8rem clamp(1.5rem, 5vw, 3rem) 4rem", fontFamily: "'Inter', sans-serif" }}>
        <h1 style={{ fontSize: "clamp(1.6rem, 3vw, 2.2rem)", fontWeight: 700, color: "#1a1a1a", marginBottom: "0.5rem" }}>
          {isPl ? "Warunki Korzystania z Usługi" : "Terms of Service"}
        </h1>
        <p style={{ fontSize: "0.8rem", color: "#aaa", marginBottom: "3rem" }}>
          {isPl ? "Ostatnia aktualizacja: czerwiec 2025" : "Last updated: June 2025"}
        </p>

        <Section title={isPl ? "1. Postanowienia ogólne" : "1. General Provisions"}>
          <P>{isPl
            ? "Niniejsze Warunki Korzystania regulują zasady dostępu i korzystania z platformy Aisthetic, świadczonej przez Etherna Sp. z o.o. z siedzibą w Polsce. Korzystanie z usługi oznacza akceptację niniejszych warunków."
            : "These Terms of Service govern access to and use of the Aisthetic platform provided by Etherna Sp. z o.o., registered in Poland. Using the service constitutes acceptance of these terms."
          }</P>
        </Section>

        <Section title={isPl ? "2. Opis usługi" : "2. Service Description"}>
          <P>{isPl
            ? "Aisthetic to narzędzie AI umożliwiające wizualizację efektów zabiegów estetycznych na podstawie przesłanego zdjęcia. Usługa dostępna jest w dwóch wariantach:"
            : "Aisthetic is an AI tool that enables visualization of aesthetic treatment effects based on an uploaded photo. The service is available in two variants:"
          }</P>
          <ul style={{ paddingLeft: "1.5rem", marginBottom: "0.75rem" }}>
            <Li>{isPl ? "Wersja B2C — dla użytkowników indywidualnych (dostępna wkrótce)" : "B2C version — for individual users (coming soon)"}</Li>
            <Li>{isPl ? "Wersja B2B — dla gabinetów medycyny estetycznej i klinik" : "B2B version — for aesthetic medicine clinics"}</Li>
          </ul>
        </Section>

        <Section title={isPl ? "3. Warunki korzystania" : "3. Conditions of Use"}>
          <P>{isPl ? "Użytkownik zobowiązuje się do:" : "The user agrees to:"}</P>
          <ul style={{ paddingLeft: "1.5rem", marginBottom: "0.75rem" }}>
            <Li>{isPl ? "Korzystania z usługi zgodnie z obowiązującym prawem" : "Using the service in accordance with applicable law"}</Li>
            <Li>{isPl ? "Nieprzesyłania zdjęć osób trzecich bez ich zgody" : "Not uploading photos of third parties without their consent"}</Li>
            <Li>{isPl ? "Nieprzetwarzania wyników wizualizacji w celach sprzecznych z prawem" : "Not using visualization results for unlawful purposes"}</Li>
            <Li>{isPl ? "Niepodjęcia prób naruszenia bezpieczeństwa systemu" : "Not attempting to breach system security"}</Li>
          </ul>
        </Section>

        <Section title={isPl ? "4. Charakter wizualizacji" : "4. Nature of Visualizations"}>
          <P>{isPl
            ? "Wizualizacje generowane przez Aisthetic mają wyłącznie charakter poglądowy i informacyjny. Nie stanowią porady medycznej, diagnozy ani gwarancji efektów rzeczywistego zabiegu. Ostateczny wygląd po zabiegu może różnić się od wygenerowanej wizualizacji i zależy od indywidualnych cech pacjenta oraz umiejętności lekarza."
            : "Visualizations generated by Aisthetic are for illustrative and informational purposes only. They do not constitute medical advice, diagnosis, or a guarantee of actual treatment results. The final appearance after treatment may differ from the generated visualization and depends on individual patient characteristics and the physician's skills."
          }</P>
        </Section>

        <Section title={isPl ? "5. Własność intelektualna" : "5. Intellectual Property"}>
          <P>{isPl
            ? "Wszelkie prawa własności intelektualnej do platformy Aisthetic, w tym algorytmy AI, interfejs, grafiki i treści, należą do Etherna Sp. z o.o. Zabronione jest kopiowanie, modyfikowanie lub rozpowszechnianie elementów platformy bez pisemnej zgody."
            : "All intellectual property rights to the Aisthetic platform, including AI algorithms, interface, graphics, and content, belong to Etherna Sp. z o.o. Copying, modifying, or distributing elements of the platform without written consent is prohibited."
          }</P>
        </Section>

        <Section title={isPl ? "6. Ograniczenie odpowiedzialności" : "6. Limitation of Liability"}>
          <P>{isPl
            ? "Aisthetic nie ponosi odpowiedzialności za decyzje medyczne podjęte na podstawie wygenerowanych wizualizacji. Platforma nie zastępuje konsultacji lekarskiej. W maksymalnym zakresie dopuszczalnym przez prawo, nasza odpowiedzialność jest ograniczona do wartości usługi wykupionej przez użytkownika."
            : "Aisthetic is not responsible for medical decisions made based on generated visualizations. The platform does not replace medical consultation. To the maximum extent permitted by law, our liability is limited to the value of the service purchased by the user."
          }</P>
        </Section>

        <Section title={isPl ? "7. Dostępność usługi" : "7. Service Availability"}>
          <P>{isPl
            ? "Dokładamy starań, aby platforma była dostępna nieprzerwanie. Zastrzegamy sobie prawo do przerw technicznych, aktualizacji lub modyfikacji usługi bez wcześniejszego powiadomienia."
            : "We strive to keep the platform continuously available. We reserve the right to technical interruptions, updates, or service modifications without prior notice."
          }</P>
        </Section>

        <Section title={isPl ? "8. Ochrona danych osobowych" : "8. Personal Data Protection"}>
          <P>{isPl
            ? "Przetwarzanie danych osobowych odbywa się zgodnie z naszą Polityką Prywatności oraz przepisami RODO. Szczegółowe informacje znajdziesz na stronie Polityki Prywatności."
            : "Personal data processing is carried out in accordance with our Privacy Policy and GDPR regulations. Details can be found on the Privacy Policy page."
          }</P>
        </Section>

        <Section title={isPl ? "9. Zmiany warunków" : "9. Changes to Terms"}>
          <P>{isPl
            ? "Zastrzegamy sobie prawo do zmiany niniejszych warunków. O istotnych zmianach będziemy informować z wyprzedzeniem za pośrednictwem strony lub e-mailem."
            : "We reserve the right to change these terms. We will notify you of significant changes in advance via the website or email."
          }</P>
        </Section>

        <Section title={isPl ? "10. Prawo właściwe" : "10. Governing Law"}>
          <P>{isPl
            ? "Niniejsze warunki podlegają prawu polskiemu. Wszelkie spory będą rozstrzygane przez właściwe sądy polskie."
            : "These terms are governed by Polish law. Any disputes will be resolved by the competent Polish courts."
          }</P>
        </Section>

        <Section title={isPl ? "11. Kontakt" : "11. Contact"}>
          <P>{isPl
            ? "W sprawie warunków korzystania skontaktuj się z nami: kontakt@aisthetic.ai"
            : "For questions about these terms, contact us at: kontakt@aisthetic.ai"
          }</P>
        </Section>
      </div>
      <Footer />
    </div>
  );
}